- docker/postgres/Dockerfile
- src/postgres/Makefile
- src/postgres/functions.sh
- terraform-dev/bigquery-publishing.tf
- terraform-dev/bigquery.tf
- terraform-staging/bigquery-publishing.tf
- terraform-staging/bigquery.tf
- terraform/bigquery-publishing.tf
- terraform/bigquery.tf
This will make the data available without having to wait an hour for the
database to restore, and without having to pay for an always-on postgres
database.
> Export all publishing database tables to BigQuery

- src/mongodb/Makefile
- src/mongodb/sh/content_items.sh
- terraform-dev/bigquery-content.tf
- terraform-staging/bigquery-content.tf
- terraform/bigquery-content.tf
This will make the data available without having to wait for the
database to restore, and without having to pay for an always-on mongodb
database.
> Export all of mongodb to BigQuery

- src/mongodb/Makefile
- src/mongodb/js/organisation_govuk_status.js
- src/mongodb/sh/organisation_govuk_status.sh
- terraform-dev/bigquery-content.tf
- terraform-staging/bigquery-content.tf
- terraform/bigquery-content.tf
Close #326
This doesn't incorporate the status into any of the derived tables in
the `graph` or `search` tables.  That can wait.
> Export organisation-govuk-status from mongo to BQ

- terraform-dev/bigquery-content.tf
- terraform-dev/bigquery-graph.tf
- terraform-dev/bigquery-publishing.tf
- terraform-dev/bigquery.tf
- terraform-staging/bigquery-content.tf
- terraform-staging/bigquery-graph.tf
- terraform/bigquery-content.tf
- terraform/bigquery-graph.tf
Purpose of this commit is to grant BigQuery read permissions in the development environment to an additional service account from the metadata project. 
The intent is to grant the same permissions to: 
- 'wif-ner-new-content-inference@cpto-content-metadata.iam.gserviceaccount.com' 
as have been granted to:  
- 'cpto-content-metadata-sa@cpto-content-metadata.iam.gserviceaccount.com'. 
Specifically, these permissions enable the service account to read from bigquery content and graph datasets.
Additionally, some formatting changes have been made to files `bigquery-publishing.tf` and `bigquery.tf` courtesy of `terraform fmt`.
> Grant access to additional metadata project service account

- terraform-staging/environment.auto.tfvars
Access to the govsearch app is currently restricted to named users.
This commit removes their access, and instead allows all members of the
Data Products google group.
> Allow data products team to access app in staging

- terraform-dev/bigquery-content.tf
- terraform-dev/bigquery-graph.tf
- terraform-staging/bigquery-content.tf
- terraform-staging/bigquery-graph.tf
- terraform/bigquery-content.tf
- terraform/bigquery-graph.tf
Purpose of this PR is to grant BigQuery read permissions in all the environments to a new service account (specific to the NER bulk inference pipeline) from the GCP metadata project and remove permissions from the old GCP metadata project service account.
Specifically, these permissions enable the service account to read from bigquery content and graph datasets.
> grant roles/bigquery.dataViewer to the new NER bulk inference service account

- terraform-dev/bigquery-content.tf
- terraform-dev/bigquery-graph.tf
- terraform-staging/bigquery-content.tf
- terraform-staging/bigquery-graph.tf
- terraform/bigquery-content.tf
- terraform/bigquery-graph.tf
Purpose of this PR is to grant BigQuery read permissions in all the environments to a new service account from the GCP question-answering with large-language-models.
Specifically, these permissions enable the service account to read from bigquery search and graph datasets.
> grant bigquery.DataViewer role to the service account for llm-question-answering project

- terraform/workflow.tf
Fix a syntax error introduced in https://github.com/alphagov/govuk-knowledge-graph-gcp/pull/451.  The error is only in the production environment.
The [Tables metadata](https://console.cloud.google.com/monitoring/alerting/policies/7462025334159841691?project=govuk-knowledge-graph) check is raising an alert because the table `content.bank_holiday_url` hasn't been updated for more than 24 hours, because of the syntax error in the
[workflow](https://console.cloud.google.com/workflows/workflow/europe-west2/bank-holidays/logs?project=govuk-knowledge-graph-dev).
The workflow doesn't report any errors. Perhaps it is only concerned with the success of the API call to BigQuery, not the success of the query itself.
> Fix bank holiday workflow

- src/mongodb/Makefile
- src/mongodb/bigquery/page.sql
- src/mongodb/bigquery/taxon.sql
- src/mongodb/sh/internal_name.sh
- terraform-dev/bigquery-content.tf
- terraform-dev/bigquery-graph.tf
- terraform-dev/bigquery-search.tf
- terraform-dev/bigquery/page.sql
- terraform-dev/bigquery/taxon.sql
- terraform-dev/bigquery/thing.sql
- terraform-staging/bigquery-content.tf
- terraform-staging/bigquery-graph.tf
- terraform-staging/bigquery-search.tf
- terraform-staging/bigquery/page.sql
- terraform-staging/bigquery/taxon.sql
- terraform-staging/bigquery/thing.sql
- terraform/bigquery-content.tf
- terraform/bigquery-graph.tf
- terraform/bigquery-search.tf
- terraform/bigquery/page.sql
- terraform/bigquery/taxon.sql
- terraform/bigquery/thing.sql
The PR consists of steps to add a new data (internal_name) field to search.taxon table to be available for UI search.
> Use details.internal_name instead to disambiguate taxon titles

- terraform-dev/bigquery/page.sql
- terraform-dev/bigquery/taxon.sql
- terraform-dev/bigquery/thing.sql
- terraform-staging/bigquery/page.sql
- terraform-staging/bigquery/taxon.sql
- terraform-staging/bigquery/thing.sql
- terraform/bigquery/page.sql
- terraform/bigquery/taxon.sql
- terraform/bigquery/thing.sql
The purpose of this PR is to fix relevant SQL used to populate a page name.
The SQL has been updated to ensure that the page title is used where it is unique **OR** where the page internal name is not available.
> Fix titles sql

- terraform-dev/govgraphsearch.tf
- terraform-dev/main-gcp.tf
- terraform-staging/govgraphsearch.tf
- terraform-staging/main-gcp.tf
- terraform/govgraphsearch.tf
- terraform/main-gcp.tf
- Assign projectOwner role to group not individuals
- Set support email of GovSearch app to a group
This avoids revealing owners in the public GitHub repository, and makes it
easier to change people's permissions, by avoiding terraform.
> Assign owner and support emails to groups

- .github/workflows/diff-terraform.yml
- README.md
- diff-exclude
- diff-terraform.sh
We try to keep the terraform configuration as similar as possible across
environments.  This commit:
- states this policy in the README
- provides a command to check for unintended differences
- configures a GitHub Action to check pull requests
> Explain how to check terraform across environments

- terraform-dev/bigquery-content.tf
- terraform-dev/bigquery/thing.sql
- terraform-staging/bigquery-content.tf
- terraform-staging/bigquery/thing.sql
- terraform/bigquery-content.tf
Abbreviations were added in #437 and #440 but by accident those changes
weren't made consistently in all environments (prod, staging, dev).
This commit makes it consistent.
The table `content.abbreviations` also wasn't terraformed by those pull
requests, as noted in #494.
Closes #494
> Terraform abbreviations table and things query

- diff-terraform.sh
- terraform-dev/terraform.tfvars
This adds one line to one file in one environment.  It enables an API
that is already enabled anyway, because terraform doesn't disable APIs
when they are removed from the configuration as this line was.  So there
will be nothing to deploy, and no actual real-world change except that
the `diff-terraform` GitHub Action should now pass.
This PR also includes a bugfix for the `diff-terraform.sh` tool, which was exiting with an error even when diffs were blank, because blank diffs included whitespace.
> Make terraform consistent in all environments

- terraform-dev/bigquery/check-tables-metadata.sql
- terraform-staging/bigquery/check-tables-metadata.sql
- terraform/bigquery/check-tables-metadata.sql
We create alerts when a table unexpectedly has zero rows. We also update
tables by first truncating them (removing all rows), and then loading
new data into them. Alerts can be raised between those two events
occurring.
Unfortunately, there isn't a way to truncate and load in the same
transaction, so that the table always has rows, and if the load fails
then the original rows remain.
- The `WRITE_TRUNCATE` disposition of `bq load` unfortunately scrubs the
schema of the table as well as the data.
- The `TRUNCATE` statement in SQL isn't allowed as part of a
multi-statement transaction.
So this commit introduces a hard-coded tolerance.  Alerts will only be
raised for an empty tables if more than 10 minutes have passed since
they were last updated.
Closes #491
> Tolerate tables being briefly empty during updates

- terraform-dev/govgraphsearch.tf
- terraform-staging/govgraphsearch.tf
- terraform/govgraphsearch.tf
This PR introduces the `NODE_ENV` environment variable to the Cloud Run instance.
It is used for the frontend to know which environment it is being served from. See [this PR](https://github.com/alphagov/govuk-knowledge-graph-search/pull/73).
> Define node env

- README.md
This commit edits the README to meet the [Standard
README](https://github.com/RichardLitt/standard-readme) conventions.
This was encouraged by the GOV.UK 2nd line team.  Some detailed content
has been migrated to the [Data Community Tech
Docs](https://docs.data-community.publishing.service.gov.uk/tools/govgraph/).
> Meet the 'standard README' conventions

- src/mongodb/bigquery/taxon.sql
- terraform-dev/bigquery/thing.sql
- terraform-staging/bigquery/thing.sql
- terraform/bigquery/thing.sql
Deprecated taxons are identified with a `phase` value of `alpha` in graph.page.
The purpose of the proposed changes is to ensure that deprecated taxons are not displayed to end users.
This is achieved by:
- Using a `WHERE` filter to prevent deprecated taxons from being included in the creation of `graph.taxon` (`taxon.sql`)
- Using a `WHERE` filter to prevent deprecated taxons from being included in the population of `search.thing` (`thing.sql`)
> Omit deprecated taxons

- terraform-dev/bigquery.tf
- terraform-staging/bigquery.tf
- terraform/bigquery.tf
We now have a Google Group of the developers who work on the GovSearch.
It would be more appropriate to send alerts to that group than to the
whole Data Products team.
> Alert GovSearch Devs instead of Data Products

- terraform-dev/bigquery-content.tf
- terraform-dev/bigquery-graph.tf
- terraform-dev/bigquery-publishing.tf
- terraform-dev/bigquery-search.tf
- terraform-dev/bigquery.tf
- terraform-dev/main-gcp.tf
- terraform-staging/bigquery-content.tf
- terraform-staging/bigquery-graph.tf
- terraform-staging/bigquery-publishing.tf
- terraform-staging/bigquery-search.tf
- terraform-staging/bigquery.tf
- terraform-staging/main-gcp.tf
- terraform/bigquery-content.tf
- terraform/bigquery-graph.tf
- terraform/bigquery-publishing.tf
- terraform/bigquery-search.tf
- terraform/bigquery.tf
- terraform/main-gcp.tf
Currently we assign the bigquery.dataViewer to three different Google
Groups, each of which is managed independently of GovSearch.  It would
be better to create a single Google Group called govsearch-data-viewers,
and make those other groups members of govsearch-data-viewers.  Such a
group has been created, and this commit reconfigures terraform to use
it.
> Consolidate some bigquery dataViewer roles

- src/mongodb/Makefile
BigQuery table export files are no longer concatenated since
98a7c38d90dba088097261d1f57b5a92076697ea
> Correct an out-of-date comment

- src/mongodb/bigquery/content.sql
Guide pages have several parts, each with their own slug.  A URL without
any slug uses the content of the first part.  We were inferring the
wrong content because of an off-by-one error.
You can confirm that parts are zero-indexed by the following query.
```sql
SELECT
base_path,
MIN(part_index) AS first_index
FROM
content.parts_content
GROUP BY
base_path
HAVING
first_index > 0;
```
> Fix wrong content for guide pages without slug

- terraform-dev/environment.auto.tfvars
- terraform-dev/govgraphsearch.tf
- terraform-dev/main-gcp.tf
- terraform-staging/environment.auto.tfvars
- terraform-staging/govgraphsearch.tf
- terraform-staging/main-gcp.tf
- terraform/environment.auto.tfvars
- terraform/govgraphsearch.tf
- terraform/main-gcp.tf
For GA4 Google Analytics
These aren't secret.  They're shown in plain text in the browser "view
source".
> Add GTM variables to the govsearch environment

- terraform-staging/environment.auto.tfvars
This allows a Google account that we created for user research
participants to access the app in the staging environment.
> Allow a test google account through IAP

- terraform-dev/main-gcp.tf
- terraform-staging/main-gcp.tf
- terraform/main-gcp.tf
This has no effect on the terraform plan, but makes the configuration clearer.
> Use bool data type for true/false tfvars

- terraform-dev/bigquery/page.sql
- terraform-staging/bigquery/page.sql
- terraform/bigquery/page.sql
Include both embedded and expanded links in search.
This is achieved by:
1. Fetching both embedded and expanded links into a single table;
2. Deduplicating the table, and
3. Aggregating the link target values into a list, grouped by source url
> Include expanded links

- terraform-dev/queries/load_bank_holiday_titles.sql
- terraform-dev/queries/load_bank_holiday_url.sql
- terraform-staging/queries/load_bank_holiday_titles.sql
- terraform-staging/queries/load_bank_holiday_url.sql
- terraform/queries/load_bank_holiday_titles.sql
- terraform/queries/load_bank_holiday_url.sql
SQL was missing a "+" sign in replace statements due to a lazy "find/replace" operation on a previous PR.
The "+" symbol has been reinstated.
> Fix SQL bank holiday queries

- terraform-dev/bigquery/organisation.sql
- terraform-dev/schemas/search/organisation.json
- terraform-staging/bigquery/organisation.sql
- terraform-staging/schemas/search/organisation.json
- terraform/bigquery/organisation.sql
- terraform/schemas/search/organisation.json
This PR addresses an issue whereby some records are duplicated in the `search.organisations` table because a single organisation may have multiple parents.
The PR implements a fix which consolidates parent names into a list to ensure that each organisation record remains distinct in the table.
Specifically, the following changes have been made:
- SQL statements used to populate the `parentName` column has been amended to consolidate multiple values into a list
- Name of parent column has been changed from `parentName` to `parentNames` (in both the SQL and the `search.organisations` schema).
**Note** that this change will have the following impact on the application front-end: 
- `Organisation` type as described in [search-api-types](https://github.com/alphagov/govuk-knowledge-graph-search/ …
> [DO NOT MERGE YET] Make search.organisation distinct on name

- terraform-dev/bigquery/page.sql
- terraform-staging/bigquery/page.sql
- terraform/bigquery/page.sql
Omitting these from GovSearch link search seems to have been an
oversight, given that we include all expanded links, which might not
even be rendered on the page.  Also, at least one user expected the
start button links to be included.
> Include start buttons in link search

- terraform-dev/bigquery/page.sql
- terraform-staging/bigquery/page.sql
- terraform/bigquery/page.sql
`page.sql` currently refers to a table (`transaction_start_links`) which doesn't exist.
The SQL should instead refer to the `transaction_start_link` table.
`page.sql` has been updated with the correct table name.
**This change has been tested and is working in staging.**
> Fix reference to transaction_start_link

- terraform-dev/bigquery/page.sql
- terraform-dev/schemas/search/page.json
- terraform-staging/bigquery/page.sql
- terraform-staging/schemas/search/page.json
- terraform/bigquery/page.sql
- terraform/schemas/search/page.json
Purpose of this PR is to introduce changes which update the `search.page` BigQuery table to include `link_type` (e.g. 'embedded') in addition to `link_url`.
`search.page` currently includes a `hyperlinks` field which contains an array of URL strings for hyperlinks in a given page.
This change updates the type of the `hyperlinks` column such that it is now an array of records, which contains both of: 
- The link URL (`link_url`); and
- The link type (`link_type`).
Specifically, the following changes have been made: 
- **Updated table schema**: the schema for `search.page` has been updated to reflect that the `hyperlinks` field will now contain record-type values instead of strings
- **Updated SQL**: SQL used to populate the `search.page` table has been updated to populate the `link_type` …
> [DO NOT MERGE YET] Links by type

- src/mongodb/sh/content_items.sh
I accidentally neglected to do this, so the table has been growing every
day, and now costs about £3/day in BigQuery storage.
https://trello.com/c/VefK1GNi/126-investigate-rising-bigquery-storage-cost
To check that it works, I force-pushed this branch to the `dev` branch, then
manually triggered the mongodb workflow, and then looked at the output of
```sql
SELECT *
FROM `govuk-knowledge-graph-dev.test.tables-metadata`;
```
to confirm that the table no longer has way more rows than any other table, and
that the tables that I'd expect to have been updated by the mongodb workflow
have been.
I'll also force-push to the `staging` branch, wait for the overnight batch, and
check in the morning that there are no alerts.
> Truncate content_items table before repopulating

- docker/postgres/Dockerfile
Closes #458.
See the comment in src/postgres/functions.sh for why we didn't end up
using duckdb.
> We have to use uncompressed CSV for the largest table, so we might as well
> use it for the others too.
>
> BigQuery can't deal with compressed CSVs larger than 4GB.  The largest table
> is 19GB when compressed.
>
> Alternatively we could use Parquet (via DuckDB) but BigQuery can't cope with
> values larger than 10MiB in any particular column, and the largest page has
> 11302027 bytes (>10MiB) in the `details` column.
>
> /hmrc-internal-manuals/customs-authorisation-and-approval/caa08030
>
> https://webarchive.nationalarchives.gov.uk/ukgwa/20211120003440/https://www.gov.uk/hmrc-internal-manuals/customs-authorisation-and-approval/caa08030
>
> The DuckDB max_line_size parameter defaults to 2 …
> Remove duckdb from postgres Dockerfile

- terraform-dev/govgraphsearch.tf
- terraform-dev/main-gcp.tf
- terraform-dev/storage.tf
- terraform-staging/govgraphsearch.tf
- terraform-staging/main-gcp.tf
- terraform-staging/storage.tf
- terraform/govgraphsearch.tf
- terraform/main-gcp.tf
- terraform/storage.tf
This service account is already in use by the GitHub Actions of the
repository https://github.com/alphagov/govuk-knowledge-graph-search
It needs the roles/permissions that are documented here:
https://cloud.google.com/run/docs/reference/iam/roles#additional-configuration
Edit 2023-10-31: because it's deploying from source, it also needs the roles/permissions that are documented here: https://cloud.google.com/run/docs/deploying-source-code#permissions_required_to_deploy
[Trello card](https://trello.com/c/nwWkD5d6/121-terraform-govsearch-ci-cd-service-accounts)
Also closes #405
> Terraform the service account for CI/CD

- terraform-dev/govgraphsearch.tf
- terraform-staging/govgraphsearch.tf
- terraform/govgraphsearch.tf
We have been storing service account keys in GCP secrets, because
otherwise they are only visible once.  But we don't need them to be
visible more than once.
1. Create key
2. Store it in a GitHub secret for a GitHub Action
3. Forget about it
4. If we accidentally delete the GitHub secret, we can easily create a
new service account key.
We ought to rotate the keys periodically anyway, and ideally we'd use
keyless authentication via Workload Identity Federation.
> Don't store service account keys

- docker/mongodb/run.sh
PR #546 inadvertently hardcoded the name of the bucket from which the
mongo instance downloads a database backup file.  This meant it only ran
in the dev environment, not the others.
> Don't hardcode bucket name for mongo instance

- terraform-dev/workflows/govuk-integration-database-backups.yaml
- terraform-staging/workflows/govuk-integration-database-backups.yaml
- terraform/workflows/govuk-integration-database-backups.yaml
A workflow that responds to the creation of these files needs to know
its exact name.  The format of the part of the name that represents time
has recently changed.
> Update filename of Publishing API database backup

- terraform-dev/gce.tf
- terraform-dev/workflow.tf
- terraform-staging/gce.tf
- terraform-staging/workflow.tf
- terraform/gce.tf
- terraform/workflow.tf
Update the changes in #566 to make the redis-cli virtual machine
template optional, using the same setting that makes redis itself
optional.
Without this commit, it isn't possible to apply the same terraform
configuration to the staging environment, where redis is disabled
(because it isn't integrated with Signon's staging environment.)
> fix: Make redis-cli contingent on redis existing

- src/mongodb/bigquery/hyperlinks_to.sql
We create records in the 'graph.page' table of pages that have content. Then we add more records of pages that don't have content but do exist as the target of hyperlinks. By mistake, we were creating duplicates when the same page was the target of multiple hyperlinks.  This was noticed for the homepage, with the following query.
```sql
SELECT *
FROM `govuk-knowledge-graph.graph.page`
WHERE url = "https://www.gov.uk"
```
Thanks to @exfalsoquodlibet for reporting the bug.
> Don't create duplicate pages from hyperlinks

- src/mongodb/bigquery/page.sql
[Trello](https://trello.com/c/1MIvFqE2/65-dont-put-part-suffix-on-document-type-of-subpages)
Remove the `_part` suffix from subpages of `guide` and
`travel_advice` documents. It didn't turn out to be useful, and it
confused users of GovSearch, who expected all matching parts of a guide
to be shown when filtered for document_type=guide, rather than only the
first page.
> feat: Don't suffix the document type of page parts

- terraform-dev/gce.tf
- terraform-staging/gce.tf
- terraform/gce.tf
We never terraformed the firewalls that Google created automatically in the
'default' network.  We also don't need them.  The one that allows SSH can be
replaced by one that allows SSH via IAP, which is more secure, and is consistent
with how SSH via IAP is configured for the 'redis-cli' instance in the
'cloudrun' network.
1. Terraform the default firewalls
2. Delete the default firewalls
3. Allow SSH via IAP on the 'default' network
> chore: terraform default firewalls

- terraform-dev/bigquery-functions.tf
- terraform-staging/bigquery-functions.tf
- terraform/bigquery-functions.tf
The terraform configuration of a BigQuery function mistakenly loaded a
javascript library from a bucket in the dev project, instead of loading
it from a bucket in the same project as the function belongs to.
> fix: scope bucket to project

- .github/workflows/docker-parse-html-dev.yml
- .github/workflows/docker-parse-html-staging.yml
- .github/workflows/docker-parse-html.yml
- .github/workflows/ruby-lint-and-test.yml
- docker/parse-html/.dockerignore
- docker/parse-html/.rubocop.yml
- docker/parse-html/Dockerfile
- docker/parse-html/Gemfile
- docker/parse-html/Gemfile.lock
- docker/parse-html/README.md
- docker/parse-html/app.rb
- docker/parse-html/spec/app_spec.rb
- terraform-dev/bigquery/parse-html.sql
- terraform-dev/cloud-run.tf
- terraform-staging/bigquery/parse-html.sql
- terraform-staging/cloud-run.tf
- terraform/bigquery/parse-html.sql
- terraform/cloud-run.tf
[Trello](https://trello.com/c/V5kpeEn0/192-make-govspeak-and-html-scripts-available-to-bigquery)
Implements part of https://github.com/alphagov/govuk-knowledge-graph-gcp/issues/559
Depends on https://github.com/alphagov/govuk-knowledge-graph-gcp/pull/561
A function to parse a string of HTML passed in by BigQuery, and return things
extracted from the HTML, in the form that BigQuery expects (JSON).
BigQuery supports various kinds of custom function, depending on whether it can
be implemented in
* pure SQL
* or a programming language that is supported by Cloud Functions v2, and that
doesn't have any particular system requirements
* or a fully customised system, in Docker, hosted in Cloud Run.
We need a fully customised system, because we use Selenium with Chromedriver to
parse the HTML, and …
> feat: parse HTML and extract things such as text

- terraform-dev/cloud-function.tf
- terraform-dev/cloud-run.tf
- terraform-staging/cloud-function.tf
- terraform-staging/cloud-run.tf
- terraform/cloud-function.tf
- terraform/cloud-run.tf
The resource 'random_string' only creates one string, not one for every
time it is referenced.
> Fix: terraform bigquery jobs with random strings

- terraform/environment.auto.tfvars
Nothing in the dataset is sensitive.
> Allow users to view the publisher dataset

- terraform-dev/bigquery/parse-html.sql
- terraform-staging/bigquery/parse-html.sql
- terraform/bigquery/parse-html.sql
The parameter was missing in the BigQuery wrapper of the Cloud Function.
> fix: add url parameter to parse_html() in BigQuery

- terraform-dev/bigquery-search.tf
- terraform-dev/bigquery/document-type.sql
- terraform-dev/bigquery/locale.sql
- terraform-dev/bigquery/organisation.sql
- terraform-dev/schemas/search/document-type.json
- terraform-dev/schemas/search/locale.json
- terraform-dev/schemas/search/organisation.json
- terraform-staging/bigquery-search.tf
- terraform-staging/bigquery/document-type.sql
- terraform-staging/bigquery/locale.sql
- terraform-staging/bigquery/organisation.sql
- terraform-staging/schemas/search/document-type.json
- terraform-staging/schemas/search/locale.json
- terraform-staging/schemas/search/organisation.json
- terraform/bigquery-search.tf
- terraform/bigquery/document-type.sql
- terraform/bigquery/locale.sql
- terraform/bigquery/organisation.sql
- terraform/schemas/search/document-type.json
- terraform/schemas/search/locale.json
- terraform/schemas/search/organisation.json
Corresponds to https://github.com/alphagov/govuk-knowledge-graph-search/issues/63
It will save money by allowing GovSearch to query for exactly the data
that it needs, rather than filtering bigger datasets, which it otherwise
does for every new session.
The queries are also adapted to run from the `content` dataset (which is
raw data), rather than the `graph` dataset (which is derived data), so
that the `graph` dataset can eventually be removed.
> feat: tables to populate govsearch dropdowns

- terraform-dev/bigquery-content.tf
- terraform-dev/bigquery-graph.tf
- terraform-staging/bigquery-content.tf
- terraform-staging/bigquery-graph.tf
- terraform/bigquery-content.tf
- terraform/bigquery-graph.tf
Following
https://github.com/alphagov/govuk-knowledge-graph-search/pull/233
GovSearch only needs access to the `search` dataset.
> chore: revoke some GovSearch dataset permissions

- terraform-dev/bigquery-private.tf
- terraform-dev/bigquery-public.tf
- terraform-dev/environment.auto.tfvars
- terraform-dev/main-gcp.tf
- terraform-staging/bigquery-private.tf
- terraform-staging/bigquery-public.tf
- terraform-staging/environment.auto.tfvars
- terraform-staging/main-gcp.tf
- terraform/bigquery-private.tf
- terraform/bigquery-public.tf
- terraform/environment.auto.tfvars
- terraform/main-gcp.tf
[Trello](https://trello.com/c/mlKACiMO/112-govgraph-make-some-data-open)
Create two new BigQuery datasets, called 'private' and 'public', for
data that doesn't belong elsewhere.
An example of data that belongs in the 'private' dataset is data that is
derived from the Publishing API data in the 'publishing-api' dataset,
and that must not be publicly available.
An example of data that belongs in the 'public' dataset is data that is
derived from the Content API data in the 'content-api' dataset,
and that may be publicly available.
An example of data that doesn't belong in either the 'public' or
'private' datasets is data that is used directly by the GovSearch app.
It is better for that data to be in its own dataset, so that the
GovSearch app can be granted access to only the data that it …
> feat: bigquery datasets - private and public

- terraform-dev/bigquery.tf
- terraform-dev/bigquery/check-tables-metadata.sql
- terraform-dev/bigquery/tables-metadata.sql
- terraform-staging/bigquery.tf
- terraform-staging/bigquery/check-tables-metadata.sql
- terraform-staging/bigquery/tables-metadata.sql
- terraform/bigquery.tf
- terraform/bigquery/check-tables-metadata.sql
- terraform/bigquery/tables-metadata.sql
- Stop storing the results of the hourly check of table metadata. It
wasn't ever useful. Instead, we always look at the
`test.tables-metadata` view.
- Refactor the definition of the `test.tables-metadata` view query
to be in a separate file.
> feat: don't store table metadata check results

- src/mongodb/bigquery/page.sql
- terraform-dev/bigquery-private.tf
- terraform-dev/bigquery/page.sql
- terraform-dev/schemas/graph/page.json
- terraform-dev/schemas/graph/part.json
- terraform-staging/bigquery-private.tf
- terraform-staging/bigquery/page.sql
- terraform-staging/schemas/graph/page.json
- terraform-staging/schemas/graph/part.json
- terraform/bigquery-private.tf
- terraform/bigquery/page.sql
- terraform/schemas/graph/page.json
- terraform/schemas/graph/part.json
Page views are sensitive, so they should only be in tables in the
`private` dataset, or other datasets that are private, such as the
`search` dataset that underpins the GovSearch app.
> refactor: don't derive page views in graph dataset

- terraform-dev/bigquery-publishing-api.tf
- terraform-staging/bigquery-publishing-api.tf
- terraform/bigquery-publishing-api.tf
Partitions greatly reduce the cost of queries, and somewhat improve
their speed too.
The partition sizes have been chosen for longevity (no more than 4000
are allowed per table).
These particular partions have been chosen to support queries that
are yet to be implemented, and that will derive a table of
current editions of documents from the Publishing API database.
> feat: partition publishing-api tables

- terraform-dev/bigquery-private.tf
- terraform-dev/bigquery-public.tf
- terraform-dev/bigquery/publishing-api-editions-current.sql
- terraform-dev/schemas/private/publishing-api-editions-new-current.json
- terraform-dev/schemas/public/publishing-api-editions-current.json
- terraform-staging/bigquery-private.tf
- terraform-staging/bigquery-public.tf
- terraform-staging/bigquery/publishing-api-editions-current.sql
- terraform-staging/schemas/private/publishing-api-editions-new-current.json
- terraform-staging/schemas/public/publishing-api-editions-current.json
- terraform/bigquery-private.tf
- terraform/bigquery-public.tf
- terraform/bigquery/publishing-api-editions-current.sql
- terraform/schemas/private/publishing-api-editions-new-current.json
- terraform/schemas/public/publishing-api-editions-current.json
- Omit editions that aren't public
- Scrub information about editions that are public but that are
'redirect' or 'gone'
- Move a pre-public table into the private dataset
> fix: Scrub non-public content from editions

- terraform-dev/bigquery-public.tf
- terraform-dev/bigquery/publishing-api-editions-current.sql
- terraform-dev/schemas/public/publishing-api-editions-new-current.json
- terraform-staging/bigquery-public.tf
- terraform-staging/bigquery/publishing-api-editions-current.sql
- terraform-staging/schemas/public/publishing-api-editions-new-current.json
- terraform/bigquery-public.tf
- terraform/bigquery/publishing-api-editions-current.sql
- terraform/schemas/public/publishing-api-editions-new-current.json
New, current, online editions aren't just appended to a table. They are
also processed further, to extract the content. That means that it is
useful to keep an intermediate step between scrubbing them of non-public
data, and appending them to the main table.  That way, further
processing can use the small intermediate step, rather than
re-processing the whole main table.
> refactor: add an intermediate step before public

- terraform-dev/bigquery-public.tf
- terraform-dev/bigquery-scheduled-queries.tf
- terraform-dev/bigquery/README-extract-markup-from-editions.md
- terraform-dev/bigquery/README.md
- terraform-dev/bigquery/extract-markup-from-editions.sql
- terraform-dev/bigquery/govspeak-to-html.sql
- terraform-dev/schemas/public/markup-new.json
- terraform-dev/schemas/public/markup.json
- terraform-staging/bigquery-public.tf
- terraform-staging/bigquery-scheduled-queries.tf
- terraform-staging/bigquery/README-extract-markup-from-editions.md
- terraform-staging/bigquery/README.md
- terraform-staging/bigquery/extract-markup-from-editions.sql
- terraform-staging/bigquery/govspeak-to-html.sql
- terraform-staging/schemas/public/markup-new.json
- terraform-staging/schemas/public/markup.json
- terraform/bigquery-public.tf
- terraform/bigquery-scheduled-queries.tf
- terraform/bigquery/README-extract-markup-from-editions.md
- terraform/bigquery/README.md
- terraform/bigquery/extract-markup-from-editions.sql
- terraform/bigquery/govspeak-to-html.sql
- terraform/schemas/public/markup-new.json
- terraform/schemas/public/markup.json
Each edition has a [`schema_name`](https://docs.publishing.service.gov.uk/content-schemas.html) that governs where its content is in the 'details' column (JSON), and whether it is govspeak, or html, or both.
TODO:
> feat: extract govspeak and/or html from editions

- terraform-dev/bigquery-functions.tf
- terraform-dev/bigquery-scheduled-queries.tf
- terraform-dev/bigquery/extract-markup-from-editions.sql
- terraform-dev/bigquery/publishing-api-batch.sql
- terraform-staging/bigquery-functions.tf
- terraform-staging/bigquery-scheduled-queries.tf
- terraform-staging/bigquery/extract-markup-from-editions.sql
- terraform-staging/bigquery/publishing-api-batch.sql
- terraform/bigquery-functions.tf
- terraform/bigquery-scheduled-queries.tf
- terraform/bigquery/extract-markup-from-editions.sql
- terraform/bigquery/publishing-api-batch.sql
Instead of controlling the order of execution by scheduling one to run
an hour later than the other (for example), and hoping that the first
one doesn't take longer than an hour.
Define each query as a routine, and then schedule an overall query that
calls each routine.
Closes #633
> feat: control query execution order via routines

- .github/workflows/docker-parse-html-dev.yml
- .github/workflows/docker-parse-html-staging.yml
- .github/workflows/docker-parse-html.yml
- docker/parse-html/Dockerfile
- docker/parse-html/README.md
- docker/parse-html/app.rb
- terraform-dev/bigquery/extract-markup-from-editions.sql
- terraform-dev/embed-text.tf
- terraform-dev/parse-html.tf
- terraform-staging/bigquery/extract-markup-from-editions.sql
- terraform-staging/embed-text.tf
- terraform-staging/parse-html.tf
- terraform/bigquery/extract-markup-from-editions.sql
- terraform/embed-text.tf
- terraform/parse-html.tf
See individual commit messages.
- fix: trigger docker rebuild correctly
- fix: deploy parse-html function correctly
- fix: parse-html function correctness and speed
- chore: configure an idiomatic amount of memory
- fix: only duplicate the first part of each doc
> fix: several bugfixes

- terraform-dev/bigquery-search.tf
- terraform-staging/bigquery-search.tf
- terraform/bigquery-search.tf
No sensitive data was made wrongly accessible.
> fix: wrong permissions given to search dataset

- terraform-dev/bigquery-functions.tf
- terraform-dev/bigquery/dedup.sql
- terraform-dev/bigquery/extract-content-from-editions.sql
- terraform-dev/bigquery/taxonomy.sql
- terraform-staging/bigquery-functions.tf
- terraform-staging/bigquery/dedup.sql
- terraform-staging/bigquery/extract-content-from-editions.sql
- terraform-staging/bigquery/taxonomy.sql
- terraform/bigquery-functions.tf
- terraform/bigquery/dedup.sql
- terraform/bigquery/extract-content-from-editions.sql
- terraform/bigquery/taxonomy.sql
Otherwise we run into trouble defining it multiple times in different
queries that are called in the same batch.
> refactor: define dedup as a permanent function

- terraform-dev/artifact-registry.tf
- terraform-dev/govgraphsearch.tf
- terraform-staging/artifact-registry.tf
- terraform-staging/govgraphsearch.tf
- terraform/artifact-registry.tf
- terraform/govgraphsearch.tf
Anything older than 31 days will be deleted from the Artifact Registry,
unless it is the most-recent version.
> feat: automatically delete old docker images

- terraform-dev/bigquery-functions.tf
- terraform-dev/bigquery-public.tf
- terraform-dev/bigquery/base-path-lookup.sql
- terraform-dev/bigquery/content-batch.sql
- terraform-dev/schemas/public/base-path-lookup.json
- terraform-staging/bigquery-functions.tf
- terraform-staging/bigquery-public.tf
- terraform-staging/bigquery/base-path-lookup.sql
- terraform-staging/bigquery/content-batch.sql
- terraform-staging/schemas/public/base-path-lookup.json
- terraform/bigquery-functions.tf
- terraform/bigquery-public.tf
- terraform/bigquery/base-path-lookup.sql
- terraform/bigquery/content-batch.sql
- terraform/schemas/public/base-path-lookup.json
Create a table that maps base paths used in the real world to base paths that belong to editions in the Publishing API database.  The difference is due to documents of schema `guide` and `travel_advice` having a real-world `base_path` for each part of the document.
This depends on the table public.content, which extracts the extra slugs of `guide` and `travel_advice` documents.  The public.content table can't itself be used as a lookup table, because it omits documents that don't have content, or whose content we don't yet extract.
> feat: lookup table of real-world base paths

- terraform-dev/bigquery-functions.tf
- terraform-dev/bigquery-public.tf
- terraform-dev/bigquery/content-batch.sql
- terraform-dev/bigquery/department-analytics-profile.sql
- terraform-dev/bigquery/publishing-api-batch.sql
- terraform-dev/schemas/public/department-analytics-profile.json
- terraform-staging/bigquery-functions.tf
- terraform-staging/bigquery-public.tf
- terraform-staging/bigquery/content-batch.sql
- terraform-staging/bigquery/department-analytics-profile.sql
- terraform-staging/bigquery/publishing-api-batch.sql
- terraform-staging/schemas/public/department-analytics-profile.json
- terraform/bigquery-functions.tf
- terraform/bigquery-public.tf
- terraform/bigquery/content-batch.sql
- terraform/bigquery/department-analytics-profile.sql
- terraform/bigquery/publishing-api-batch.sql
- terraform/schemas/public/department-analytics-profile.json
Maintains a table `public.department_analytics_profle` of IDs of organisations, which happen to also be their Google Analytics ID.
- **fix: batch query was in the wrong batch**
- **feat: derive a table of Org codes**
> feat: derive a table of org codes

- docker/publishing-api/Dockerfile
- src/publishing-api/Makefile
- src/publishing-api/functions.sh
- src/publishing-api/run.sh
- terraform-dev/storage.tf
- terraform-staging/storage.tf
- terraform/storage.tf
It's so slow to restore the database, and is much quicker to use pg_dump to extract the data in a form that is nearly TSV, then clean it with sed for importing into BigQuery.  It takes about an hour, instead of about three and a half hours.
> refactor: don't restore postgres database

- README.md
- terraform-dev/bigquery.tf
- terraform-dev/environment.auto.tfvars
- terraform-dev/govgraphsearch.tf
- terraform-staging/bigquery.tf
- terraform-staging/environment.auto.tfvars
- terraform-staging/govgraphsearch.tf
- terraform/bigquery.tf
- terraform/environment.auto.tfvars
- terraform/govgraphsearch.tf
New groups:
* `govgraph-developers` replaces `govsearch-developers` as project
owners in GCP.
* `govgraph-private-data-viewers` gives read-only access to all BigQuery
datasets other than 'test', and also permission to run queries within
the projects, with the projects paying the bill.
Old groups:
* `govsearch-developers` will be deleted.
* `govsearch-data-viewers` will be deleted.
> refactor: permissions via Google Groups

- terraform-dev/bigquery/search-page.sql
- terraform-staging/bigquery/search-page.sql
- terraform/bigquery/search-page.sql
GovSearch supports filtering by taxon. It was only returning results that were themselves taxon pages, omitting pages that are tagged to taxons.  This is because a subquery wasn't using the links table to associate the taxonomy with normal pages.
> fix: get taxons of all pages, not just taxon pages

- terraform-dev/bigquery/search-page.sql
- terraform-staging/bigquery/search-page.sql
- terraform/bigquery/search-page.sql
Links such as related links (ones in the side bar) weren't returned in
search results because the query put the source URL into the table,
instead of the target URL.
> fix: GovSearch link search didn't find all links

- terraform-dev/bigquery/publishing-api-editions-current.sql
- terraform-dev/schemas/private/publishing-api-editions-new-current.json
- terraform-dev/schemas/publishing-api/editions.json
- terraform-staging/bigquery/publishing-api-editions-current.sql
- terraform-staging/schemas/private/publishing-api-editions-new-current.json
- terraform-staging/schemas/publishing-api/editions.json
- terraform/bigquery/publishing-api-editions-current.sql
- terraform/schemas/private/publishing-api-editions-new-current.json
- terraform/schemas/publishing-api/editions.json
The editions table in the upstream Publishing API database has a new column, `last_edited_by_editor_id`, created in https://github.com/alphagov/publishing-api/pull/2919. This broke the data pipeline, because the BigQuery schema of that table rejected the new column.
The new column contains sensitive data, so it is only included in tables in the `publishing-api` and `private` datasets, which most users cannot access. It is explicitly omitted from the query that puts the data into more accessible datasets.
> fix: support a new column in Publishing API table

- diff-exclude
- terraform-dev/pubsub.tf
We've created a new mirror bucket which pulls from our staging backups instead of integration. You can see this working [in the GCP console here](https://console.cloud.google.com/storage/browser/govuk-s3-mirror_govuk-database-backups).
This PR switches the terraform-dev project to subscribe to notifications on that bucket, instead of the integration one. It's the smallest change which establishes whether the process works. There will be further PRs to make this change in the other environments, and to rename the terraform resources so that they're not confusing.
> Use staging backups in terraform-dev

- diff-exclude
- terraform-staging/pubsub.tf
- terraform/pubsub.tf
This follows on from #717, and uses the GOV.UK staging backups in the knowledgegraph staging / production environments.
This PR initially targets the `use-staging-backups` branch rather than `main`, so we can either merge this first and have it update #717, or we can merge #717 and this will retarget main automatically.
> Use staging backups in staging and prod

- terraform-dev/pubsub.tf
- terraform-dev/workflow.tf
- terraform-staging/pubsub.tf
- terraform-staging/workflow.tf
- terraform/pubsub.tf
- terraform/workflow.tf
These are no longer required once they've been applied once.
Should be merged after #721 is applied.
> Remove moved blocks

- docker/publisher/Dockerfile
- src/publisher/query.js
- src/publisher/run.sh
`apt-get update` now fails in the docker image of MongoDB version 4.4.16 due to an expired signing key. That version of MongoDB is no longer supported, so the signing key is unlikely to be replaced. Upgrading to a newer docker image solves this problem.
Version compatibility check:
* We only need the package `mongodb-database-tools`, which is versioned independently of MongoDB. The version of `mongodb-database-tools` that comes in the Docker image of the latest version of MongoDB is 100.11.0.
* According to https://www.mongodb.com/docs/database-tools/mongorestore/mongorestore-compatibility-and-installation/#mongodb-server-compatibility `mongodb-database-tools` version 100.10.0 is compatible with MongoDB versions 5.0 and 4.0, so we presume that version 100.11.0 maintains that …
> chore: upgrade MongoDB docker image for publisher

- src/publisher/query.js
The table `publisher.editions` is currently empty, because the column `url` isn't nullable, but the query of the Publisher database is extracting null values in that column.
Since August 2024, there is a new, special-case document that has no slug, which is "popular links". That document is rendered as part of the homepage. When it is published to the Publishing API, its Content ID is hardcoded to `ad7968d0-0339-40b2-80bc-3ea1db8ef1b7`, and its base_path is `null`. The results of this query are joined to the Publishing API editions by base_path (or url, whatever), and null can't be joined to `null`. So, even if we were to allow nulls in the url/base_path column in BigQuery, we'd have to hardcode a special case to make the join work for the "popular links" document. It isn't worthwhile, so …
> fix: handle popular links

- terraform-dev/bigquery/page-views.sql
- terraform-staging/bigquery/page-views.sql
- terraform/bigquery/page-views.sql
Lower the cost of a daily query from about 75p to about 2p, by using alternative tables of GA4 data that have been optimised for this kind of thing.
> refactor: make page-views query cheaper

- .github/workflows/docker-support-api-staging.yml
- .github/workflows/docker-support-api.yml
The dev account number was mistakenly used in all three workflows.
> fix: correct account number in each workflow

- terraform-dev/parse-html.tf
- terraform-staging/parse-html.tf
- terraform/parse-html.tf
When changing a function's source code (usually due to dependabot),
`terraform apply` doesn't redploy the function. This is a problem that
Google isn't in a hurry to fix, so this is an attempt to work around it
with terraform's lifecycle rules.
https://github.com/hashicorp/terraform-provider-google/issues/1938#issuecomment-1229042663
> fix: redeploy functions on change to source code

- terraform-dev/bigquery/search-page.sql
- terraform-staging/bigquery/search-page.sql
- terraform/bigquery/search-page.sql
The join between Publishing API editions and Publisher editions created duplicates, because it the approximate match `STARTS_WITH()` joined different URLs, such as:
```text
https://www.gov.uk/absenoldeb-a-thal-ar-y-cyd-i-rieni-canllaw-i-gyflogwyr`
https://www.gov.uk/absenoldeb-a-thal-ar-y-cyd-i-rieni`
```
This fix terminates each URL in the join with "/" so that only complete slugs will match, such as:
```text
https://www.gov.uk/absenoldeb-a-thal-ar-y-cyd-i-rieni-canllaw-i-gyflogwyr/cymhwystra/
https://www.gov.uk/absenoldeb-a-thal-ar-y-cyd-i-rieni-canllaw-i-gyflogwyr/
```
The purpose of matching with `STARTS_WITH()` is to handle sections of `guide` and `travel_advice` documents, which each have their own URL in the `search.page` table, but are only represented by their top-level URL in …
> fix: duplicates in search.page

- src/publishing-api/README.md
- src/publishing-api/functions.sh
- src/support-api/README.md
- src/support-api/functions.sh
Closes #742. This could have been done this way in the first place, because there is no need to have a the schema in a JSON file in GitHub. The schema can be exported from BigQuery just before uploading the new data.
> refactor: truncate/load data within a transaction

- terraform/environment.auto.tfvars
A new service account replaces an old one. It calculates metrics for the
publishing pipeline.
> feat: Update service account access

- terraform-dev/gce.tf
- terraform-staging/gce.tf
- terraform/gce.tf
The local SSD ran out of space when processing the Publishing API data.
SSDs are only available in a single, fixed size of 375GiB.
This fix assumes that the greater speed (via a direct connection to the
physical host of the virtual machine) is no longer necessary since #658.
If network storage is still a bottleneck, then alternatives can be
tried:
1. Delete the extracted data once the `bq load` command has succeeded.
This might work in the short term, if the size of the
database backup file and the `table_editions.tsv` file don't
overwhelm the SSD on their own, or before any of the other files have
been deleted.
1. Connect more SSDs, and distribute the data files among them. This
would work for a longer term, until the `table_editions.tsv` file
size overwhelms the capacity of a single …
> fix: don't use local SSD for publishing-api

- terraform/environment.auto.tfvars
For fetching data from the Support API dataset.
> feat: add feedback-as-a-service service accounts

- terraform-dev/bigquery-support-api.tf
- terraform-staging/bigquery-support-api.tf
- terraform/bigquery-support-api.tf
It was accidentally included when copy-pasted from the configuration of
another dataset.
> feat: remove IAM on the Support API dataset

- docker/parse-html/README.md
- docker/parse-html/app.rb
- docker/parse-html/spec/app_spec.rb
- terraform-dev/bigquery/extract-content-from-editions.sql
- terraform-dev/schemas/public/content-new.json
- terraform-dev/schemas/public/content.json
- terraform-staging/bigquery/extract-content-from-editions.sql
- terraform-staging/schemas/public/content-new.json
- terraform-staging/schemas/public/content.json
- terraform/bigquery/extract-content-from-editions.sql
- terraform/schemas/public/content-new.json
- terraform/schemas/public/content.json
Adding two new functions following the structure of the extract_abbreviation functions as they best seem to match with is needed
Please check that the attributes and text for the returned tables and images in the functions work and at they are real attributes for the elements
> Adding that ability to return the number of images or tables on a page

- docs/terraform.md
- sync-terraform.sh
This script automatically replicates the contents of the terraform-dev project to the terraform-staging and terraform projects, excluding files and folders specified in the diff-exclude file (which includes the .terraform directory at present).
> Add terraform project synchronising script

- src/whitehall/Makefile
- src/whitehall/functions.sh
- terraform-dev/bigquery-whitehall.tf
- terraform-dev/schemas/whitehall/assets.json
- terraform-dev/schemas/whitehall/attachment_data.json
- terraform-dev/schemas/whitehall/attachments.json
- terraform-staging/bigquery-whitehall.tf
- terraform-staging/schemas/whitehall/assets.json
- terraform-staging/schemas/whitehall/attachment_data.json
- terraform-staging/schemas/whitehall/attachments.json
- terraform/bigquery-whitehall.tf
- terraform/schemas/whitehall/assets.json
- terraform/schemas/whitehall/attachment_data.json
- terraform/schemas/whitehall/attachments.json
Added:
- attachments
- assets
- attachment_data
These tables, alongside the upcoming data from Asset Manager (pipeline TBD), should give us a good picture of the state of assets.
[Trello](https://trello.com/c/EmdtD0tK/3523-replicate-part-of-the-whitehall-database-in-google-bigquery)
> Add additional tables for whitehall data pipeline

- src/whitehall/functions.sh
Some of the values we receive in the title field look like `Peer review of  \"some other thing\"` or `string \n string` (for long titles), tripping up our bq load from the csv. This commit replaces any occurrences of `\"` with `` and any occurrences of `\n` with ` `. A slight mismatch in the title should be ok, since we mostly care about matching IDs for the monitoring tool we're using the data pipeline for.
[Trello](https://trello.com/c/EmdtD0tK/3523-replicate-part-of-the-whitehall-database-in-google-bigquery)
> Fix escaped characters in whitehall data pipeline attachments table

- src/whitehall/functions.sh
Doubling quotes as per https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-csv#csv-options and adding a flag to deal with new lines.
[Trello](https://trello.com/c/EmdtD0tK/3523-replicate-part-of-the-whitehall-database-in-google-bigquery)
> Fix escaped characters and new lines in whitehall data pipeline tables

- terraform/environment.auto.tfvars
Currently only members of https://groups.google.com/a/digital.cabinet-office.gov.uk/g/govgraph-developers have access. This PR would widen access to include https://groups.google.com/a/digital.cabinet-office.gov.uk/g/govgraph-private-data-readers, which is everyone in GOV.UK.
> feat: widen access to Whitehall and Asset Manager

- terraform-dev/http-to-bucket.tf
- terraform-staging/http-to-bucket.tf
- terraform/http-to-bucket.tf
This used to work, but now more permission is required.
> fix: cloud run deploy github action permissions

- terraform-dev/bigquery/extract-content-from-editions.sql
- terraform-dev/bigquery/publishing-api-editions-current.sql
- terraform-staging/bigquery/extract-content-from-editions.sql
- terraform-staging/bigquery/publishing-api-editions-current.sql
- terraform/bigquery/extract-content-from-editions.sql
- terraform/bigquery/publishing-api-editions-current.sql
The Publishing API never re-uses an `edition_id`. But it is possible for GovGraph to see an `edition_id` appear alongside one `document_id` in one Publishing API database dump file, and a alongside a different `document_id` in a subsequent dump file. This causes the same `edition_id` to appear in multiple rows of certain tables, which causes subsequent queries to fail.
1. The production Publishing API is replicated into the Staging environment.
2. A test creates a new edition in the staging environment, with `edition_id=123` and `document_id=456`.
3. A backup of the database is created from the staging environment.
4. GovGraph ingests the new backup and sees a record with `edition_id=123` and `document_id=456`.
5. A new edition is created in the production environment that uses the same …
> fix: handle the re-use of edition IDs

- terraform-dev/bigquery/publishing-api-links-current.sql
- terraform-staging/bigquery/publishing-api-links-current.sql
- terraform/bigquery/publishing-api-links-current.sql
[Publishing API ADR-009 Step 8](https://github.com/alphagov/publishing-api/blob/main/docs/arch/adr-009-change-linksets-primary-key-to-content-id.md#8---stop-writing-to-the-link_set_id-column)
Use `publishing_api.links.link_set_content_id` directly, instead of using `publishing_api.links.link_set_id` to get `publishing_api.link_sets.content_id`.
> refactor: ready for publishing-api ADR 009 step 8

- docker/publisher/Dockerfile
- src/publisher/Makefile
- src/publisher/actions.js
- src/publisher/editions.js
- src/publisher/functions.sh
- src/publisher/run.sh
- terraform-dev/bigquery-publisher.tf
- terraform-dev/schemas/publisher/actions.json
- terraform-staging/bigquery-publisher.tf
- terraform-staging/schemas/publisher/actions.json
- terraform/bigquery-publisher.tf
- terraform/schemas/publisher/actions.json
Implements #792
Many actions are taken per new edition. For example, "request_amendments", "send_fact_check". Each of those is a row in this table. It can be joined to the "editions" table by the URL and version_number.
> feat: derive an 'actions' table from Publisher

- docker/http-to-bucket/Gemfile
- docker/http-to-bucket/app.rb
- docker/http-to-bucket/spec/app_spec.rb
Implements #803
In the http-to-bucket service, instead of only returning the the string `"Success"`, optionally return the part of an API's JSON response that matches a JMESPath expression.
> feat: return part of an API's JSON response

- src/publisher/Makefile
- src/publisher/editions.js
- terraform-dev/schemas/publisher/editions.json
- terraform-staging/schemas/publisher/editions.json
- terraform/schemas/publisher/editions.json
Mainstream Publisher editions have a type, similar to how Publishing API editions have a schema.
```text
AnswerEdition  
CampaignEdition  
CompletedTransactionEdition  
GuideEdition  
HelpPageEdition  
LicenceEdition  
LocalTransactionEdition  
PlaceEdition  
ProgrammeEdition  
SimpleSmartAnswerEdition  
TransactionEdition  
VideoEdition
```
> feat: add the document type to publisher editions

- terraform-dev/bigquery-functions.tf
- terraform-dev/bigquery-public.tf
- terraform-dev/bigquery/assets.sql
- terraform-dev/bigquery/publishing-api-batch.sql
- terraform-dev/schemas/public/assets.json
- terraform-staging/bigquery-functions.tf
- terraform-staging/bigquery-public.tf
- terraform-staging/bigquery/assets.sql
- terraform-staging/bigquery/publishing-api-batch.sql
- terraform-staging/schemas/public/assets.json
- terraform/bigquery-functions.tf
- terraform/bigquery-public.tf
- terraform/bigquery/assets.sql
- terraform/bigquery/publishing-api-batch.sql
- terraform/schemas/public/assets.json
Derive a table `public.assets` from the `details` JSON column of the `public.publishing_api_editions_current` table.
* An edition may have many attachments.
* An attachment may have many assets (often two: a document, and its thumbnail).
* Details about each asset can be looked up by joining `public.attachments.asset_manager_id` to `asset_manager.assets._id`.
Closes #796
> feat: derive assets table from Publishing API

- terraform-dev/storage.tf
- terraform-staging/storage.tf
- terraform/storage.tf
It isn't documented whether anyone needs any role for a BigQuery user-defined function to be able to fetch a Javascript library dependency from a bucket, but my guess is that any user of the function, or any service account that runs a scheduled query that uses the function, must have roles/storage.objectViewer. And someone who didn't have access to that bucket also couldn't run the function.
> fix: allow BigQuery phone number function access

- docker/http-to-bucket/app.rb
- docker/http-to-bucket/spec/app_spec.rb
The Zendesk API uses nested URL parameters, such as `page[size]=5`. When the `http-to-bucket` Cloud Run service receives a request with parameters, it uses `Rack::Utils::parse_nested_query()` to convert the parameters into a hash such as `{"page" => {"size" => "5"}}`. This was then being converted back into a URL with `URI.encode_www_form(request.params)`, which created a url-encoded version of `page={size+=>+"2"}`, and was rejected by the Zendesk API. `Rack::Utils::build_nested_query()` correctly produces a url-encoded version of `page[size]=5`.
The `expect(response.headers["Content-Type"]).to eq("text/plain; charset=utf-8")` change is unrelated. I just noticed that the test was failing, for some reason.
> fix: http-to-bucket handle nested parameters

- terraform-dev/bigquery/data-loss-prevention.sql
- terraform-staging/bigquery/data-loss-prevention.sql
- terraform/bigquery/data-loss-prevention.sql
For much greater speed and efficiency, use the largest batch permitted
by the DLP API.
> feat: Use larger batches of PII

- terraform-dev/bigquery-publishing-api.tf
- terraform-dev/schemas/publishing-api/links.json
- terraform-staging/bigquery-publishing-api.tf
- terraform-staging/schemas/publishing-api/links.json
- terraform/bigquery-publishing-api.tf
- terraform/schemas/publishing-api/links.json
Following https://github.com/alphagov/publishing-api/pull/3330.
The range-partition can't be transferred to the replacement column, which is link_set_content_id, because that is a string column. So we must do without partitions.
> feat: remove link_set_id from publisher.links

- docker/publishing-api/Dockerfile
- docker/support-api/Dockerfile
The version of `pg_dump` that AWS RDS now uses exceeds the version of `pg_restore` that we use.
Symptoms:
* Docker logs report `pg_restore:pg_restore:  error: error: unsupported version (1.16) in file header`
* Zero rows are loaded into BigQuery, so that the tables in BigQuery now have no rows.
Logging/monitoring/alerting:
* Docker logs still aren't getting into the usual GCP logs https://github.com/alphagov/govuk-knowledge-graph-gcp/issues/777
* Alert emails haven't been received for ages https://github.com/alphagov/govuk-knowledge-graph-gcp/issues/741
> chore: bump postgres version

- docker/http-to-bucket/app.rb
- docker/http-to-bucket/spec/app_spec.rb
Uses recursion to remove empty hashes from all layers of a given array or hash. This is because BigQuery can't handle the empty hashes.
This is further outlined in this issue - https://github.com/alphagov/govuk-knowledge-graph-gcp/issues/837
> Make http-to-bucket cloud function clean hashes before sending to big query
