alphagov/govuk-knowledge-graph-gcp

- terraform-staging/environment.auto.tfvars
Reverts alphagov/govuk-knowledge-graph-gcp#461 which was only done as a demonstration.
> Revert "Add Duncan to staging"

- terraform-dev/bigquery-content.tf
- terraform-dev/bigquery-graph.tf
- terraform-dev/bigquery-publishing.tf
- terraform-dev/bigquery-search.tf
- terraform-dev/bigquery.tf
- terraform-dev/bigquery/check-tables-metadata.sql
- terraform-staging/bigquery-content.tf
- terraform-staging/bigquery-graph.tf
- terraform-staging/bigquery-publishing.tf
- terraform-staging/bigquery-search.tf
- terraform-staging/bigquery.tf
- terraform-staging/bigquery/check-tables-metadata.sql
- terraform/bigquery-content.tf
- terraform/bigquery-graph.tf
- terraform/bigquery-publishing.tf
- terraform/bigquery-search.tf
- terraform/bigquery.tf
- terraform/bigquery/check-tables-metadata.sql
Errors in this query will be picked up in the logs, creating an alert.
> Schedule a query to check tables metadata

- terraform-dev/bigquery.tf
- terraform-dev/bigquery/check-tables-metadata.sql
- terraform-dev/main-gcp.tf
- terraform-dev/terraform.tfvars
- terraform-staging/bigquery-publishing.tf
- terraform-staging/bigquery.tf
- terraform-staging/bigquery/check-tables-metadata.sql
- terraform-staging/main-gcp.tf
- terraform-staging/terraform.tfvars
- terraform/bigquery-publishing.tf
- terraform/bigquery.tf
- terraform/bigquery/check-tables-metadata.sql
- terraform/main-gcp.tf
- terraform/terraform.tfvars
> Use variables for error messages to be DRY

- terraform-dev/bigquery/check-tables-metadata.sql
- terraform-staging/bigquery/check-tables-metadata.sql
- terraform/bigquery/check-tables-metadata.sql
https://trello.com/c/I6ydeMS5/2254-govsearch-incidents-2023-05-22
Some tables are expected to be empty, so don't raise an alert about
them.
> Don't alert about certain empty tables

- terraform-dev/govgraphsearch.tf
- terraform-staging/govgraphsearch.tf
- terraform/govgraphsearch.tf
It turned out that these had been configured in the dev project, but not
terraformed, so that the Cloud Run service in the other projects
couldn't access the secrets.
This commit moves the definition of the service account to the top of
the file, because it is required by the new IAM configuration further
down, and because someone might need to set up this config step by step,
as explained in the existing comments.
> Terraform IAM policies of Signon secrets

- terraform-dev/main-gcp.tf
- terraform-staging/main-gcp.tf
- terraform/main-gcp.tf
Removed explicit mention of Anthony from files enabling permissions in dev, staging, prod.
> Removed Anthony's permissions

- src/mongodb/bigquery/content.sql
- src/mongodb/bigquery/page.sql
- src/mongodb/js/parts_content.js
- terraform-dev/bigquery-graph.tf
- terraform-staging/bigquery-content.tf
- terraform/bigquery-graph.tf
Cherry picked changes to fix summary slug on travel advice
> Adapt to changed schema of travel advice pages

- terraform-dev/bigquery-content.tf
- terraform-dev/bigquery-graph.tf
- terraform-staging/bigquery-content.tf
- terraform-staging/bigquery-graph.tf
- terraform/bigquery-content.tf
- terraform/bigquery-graph.tf
Update the slug field in content.parts and graph.page to "required" in all environments.
> Change slug to REQUIRED.

- terraform-dev/govgraphsearch.tf
- terraform-staging/govgraphsearch.tf
- terraform/govgraphsearch.tf
Changes include:
- Creation of new secret (`cookie-session-signature`) to enable cookie signing
- Policy bindings allowing the appropriate service account to read the new secret value
- Data block to enable the reading of the value into the terraform config
- New environment variable for the app cloud run to enable referencing the secret as an environment variable
Relates to https://github.com/alphagov/govuk-knowledge-graph-search/pull/72#discussion_r1231442020
> Create secret for cookie signing.

- src/mongodb/bigquery/external_page.sql
- src/mongodb/bigquery/has_child_organisation.sql
- src/mongodb/bigquery/has_organisation.sql
- src/mongodb/bigquery/has_parent.sql
- src/mongodb/bigquery/has_primary_publishing_organisation.sql
- src/mongodb/bigquery/has_successor.sql
- src/mongodb/bigquery/hyperlinks_to.sql
- src/mongodb/bigquery/is_tagged_to.sql
- src/mongodb/bigquery/lines.sql
- src/mongodb/bigquery/organisation.sql
- src/mongodb/bigquery/page.sql
- src/mongodb/bigquery/person.sql
- src/mongodb/bigquery/taxon.sql
- src/mongodb/bigquery/taxon_ancestors.sql
- terraform-dev/bigquery/check-tables-metadata.sql
- terraform-dev/bigquery/page.sql
- terraform-staging/bigquery/check-tables-metadata.sql
- terraform-staging/bigquery/page.sql
- terraform/bigquery/check-tables-metadata.sql
- terraform/bigquery/page.sql
> Use TRUNCATE TABLE instead of DELETE WHERE TRUE

- terraform-dev/storage.tf
- terraform-staging/storage.tf
- terraform/storage.tf
Close #547.  We no longer manage our own certificates.
> Remove the bucket of SSL certificates

- terraform-dev/bigquery/page.sql
- terraform-staging/bigquery/page.sql
- terraform/bigquery/page.sql
[Trello](https://trello.com/c/M8oAn5UF/161-add-publishing-organisations-to-parts-pages)
GovSearch relies on "parts" of guide documents inheriting the same
metadata as the overall document, especially the publishing
organisations.  Otherwise, when a user filters by publishing
organisation, none of the parts appears in the results, because none of
them has a value for publishing organisation.
We can do this by linking via `content_id` (which is the same for each
part of a document) instead of `url` (which we construct to be different
for each part of a document).
We would be able to do this more simply if we hadn't unwisely chosen to
construct the tables `has_organisation` and
`has_primary_publishing_organisation` to use our own Frankenstein URL, a
concatenation of 'https://www.gov.uk/' …
> Include metadata in 'part' pages

- src/mongodb/Makefile
Fix dependencies of graph.page query
> fix: page table dependencies

- .github/workflows/docker-parse-html-staging.yml
- .github/workflows/docker-parse-html.yml
- terraform-dev/cloud-run.tf
- terraform-dev/main-gcp.tf
- terraform-staging/cloud-run.tf
- terraform-staging/main-gcp.tf
- terraform/cloud-run.tf
- terraform/main-gcp.tf
> fix: IAM to deploy Cloud Run from GitHub Actions

- src/publisher/query.js
One of the fixes didn't make it into the previous fix.
> fix: publisher again

- terraform-dev/bigquery/page.sql
- terraform-dev/schemas/search/page.json
- terraform-staging/bigquery/page.sql
- terraform-staging/schemas/search/page.json
- terraform/bigquery/page.sql
- terraform/schemas/search/page.json
This makes it available to the GovSearch app.
> feat: add publisher_updated_at to search.page

- terraform-dev/cloud-function.tf
- terraform-staging/cloud-function.tf
- terraform/cloud-function.tf
> chore: use IAM policy for cloud function

- terraform-dev/cloud-function.tf
- terraform-staging/cloud-function.tf
- terraform/cloud-function.tf
Otherwise terraform always plans to reconfigure it.
> chore: terraform a cloud function docker repo

- terraform-dev/artifact-registry.tf
- terraform-dev/embed-text.tf
- terraform-dev/main-gcp.tf
- terraform-dev/workload-identity-federation.tf
- terraform-staging/artifact-registry.tf
- terraform-staging/embed-text.tf
- terraform-staging/main-gcp.tf
- terraform-staging/workload-identity-federation.tf
- terraform/artifact-registry.tf
- terraform/embed-text.tf
- terraform/main-gcp.tf
- terraform/workload-identity-federation.tf
- chore: upgrade terraform google provider
- chore: fix terraform permadiff
> chore: terraform versions and glitch

- terraform/environment.auto.tfvars
For the GOV.UK Chat question answering service
> chore: grant permmissions to LLM service account

- terraform/environment.auto.tfvars
> Allow a dataform project account to view BigQuery

- terraform-dev/bigquery/search-page.sql
- terraform-staging/bigquery/search-page.sql
- terraform/bigquery/search-page.sql
The date wasn't being joined to every part of a multipart document
> fix: publisher_updated_at date on multiparts

- terraform-dev/bigquery/extract-content-from-editions.sql
- terraform-staging/bigquery/extract-content-from-editions.sql
- terraform/bigquery/extract-content-from-editions.sql
It turns out that not every step-by-step page has its content rendered
to HTML in the `details.body` field. This commit introduces a JavaScript
UDF in BigQuery to extract the content as govspeak.
`world_location_news` is now also included.
> fix: extract step-by-step content correctly

- terraform-dev/bigquery/extract-content-from-editions.sql
- terraform-staging/bigquery/extract-content-from-editions.sql
- terraform/bigquery/extract-content-from-editions.sql
It was assuming the wrong data types for some JSON elements.
It was also possible to simplify the handling of govspeak vs HTML.
Everything is extracted as though it is govspeak, even when it is HTML.
Then the 'govspeak' is rendered to HTML, which doesn't harm what was
already HTML.
More of the special cases could be supported than just guide,
travel_advice and step_by_step_nav. For example, hmrc_manual could be
supported better. But nobody has yet asked for it.
> fix: bugs in content extraction

- terraform-dev/bigquery/publishing-api-batch.sql
- terraform-staging/bigquery/publishing-api-batch.sql
- terraform/bigquery/publishing-api-batch.sql
Change CALL from content to functions to align with other calls.
> bugfix: change call from content to functions

- README.md
- docker/README.md
- docker/embed-text/README.md
- docker/publisher/README.md
- docker/publishing-api/README.md
- docs/technical-debt.md
- docs/terraform.md
- src/cloud-functions/README.md
- src/cloud-functions/govspeak-to-html/README.md
- src/publisher/README.md
- src/publishing-api/README.md
> docs: overhaul

- terraform-dev/bigquery/search-page.sql
- terraform-staging/bigquery/search-page.sql
- terraform/bigquery/search-page.sql
Omit the first 'part' of multi-part documents, which duplicates (and is
currently redirected to) the main document that has no slug. For example,
include the following:
* /main-page
* /main-page/second-part
* /main-page/third-part
Omit the following:
* /main-page/first-part
The reason to include /main-page instead of /main-page/first-part is that
no page views are recorded for /main-page/first-part.
Currently, /main-page is excluded, and /main-page/first-part is
included. This commit chooses the alternative.
> fix: Use main page of multiparts in GovSearch

- docs/how-to-write-queries.md
- terraform-dev/bigquery/README-publishing-api-links-current.md
- terraform-dev/bigquery/README-publishing-api-unpublishings-current.md
- terraform-dev/bigquery/README-taxonomy.md
- terraform-dev/bigquery/README.md
- terraform-staging/bigquery/README-publishing-api-links-current.md
- terraform-staging/bigquery/README-publishing-api-unpublishings-current.md
- terraform-staging/bigquery/README-taxonomy.md
- terraform-staging/bigquery/README.md
- terraform/bigquery/README-publishing-api-links-current.md
- terraform/bigquery/README-publishing-api-unpublishings-current.md
- terraform/bigquery/README-taxonomy.md
- terraform/bigquery/README.md
Add quite a lot of documentation about the data model, with some worked examples.
> docs: how to write queries

- terraform-dev/bigquery-search.tf
- terraform-dev/bigquery/search-batch.sql
- terraform-dev/bigquery/search-government.sql
- terraform-dev/bigquery/search-page.sql
- terraform-dev/schemas/search/government.json
- terraform-dev/schemas/search/page.json
- terraform-staging/bigquery-search.tf
- terraform-staging/bigquery/search-batch.sql
- terraform-staging/bigquery/search-government.sql
- terraform-staging/bigquery/search-page.sql
- terraform-staging/schemas/search/government.json
- terraform-staging/schemas/search/page.json
- terraform/bigquery-search.tf
- terraform/bigquery/search-batch.sql
- terraform/bigquery/search-government.sql
- terraform/bigquery/search-page.sql
- terraform/schemas/search/government.json
- terraform/schemas/search/page.json
> feat: add history-mode columns to search.page

- terraform/environment.auto.tfvars
> Adding service account for Google Looker Proof of Concept

- .github/workflows/actionlint.yml
- .github/workflows/docker-govspeak-to-html-dev.yml
- .github/workflows/docker-govspeak-to-html-staging.yml
- .github/workflows/docker-govspeak-to-html.yml
- .github/workflows/docker-html-to-text-dev.yml
- .github/workflows/docker-html-to-text-staging.yml
- .github/workflows/docker-html-to-text.yml
- .github/workflows/docker-parse-html-dev.yml
- .github/workflows/docker-parse-html-staging.yml
- .github/workflows/docker-parse-html.yml
- .github/workflows/docker-publisher-dev.yml
- .github/workflows/docker-publisher-staging.yml
- .github/workflows/docker-publisher.yml
- .github/workflows/docker-publishing-api-dev.yml
- .github/workflows/docker-publishing-api-staging.yml
- .github/workflows/docker-publishing-api.yml
- .github/workflows/docker-redis-cli-dev.yml
- .github/workflows/docker-redis-cli-staging.yml
- .github/workflows/docker-redis-cli.yml
- .github/workflows/docker-support-api-dev.yml
- .github/workflows/docker-support-api-staging.yml
- .github/workflows/docker-support-api.yml
Bulk Update: Addresses govuk-infrastructure#1361
> Add Actionlint Checks

- README.md
- terraform-dev/logs.tf
- terraform-dev/main-gcp.tf
- terraform-staging/logs.tf
- terraform-staging/main-gcp.tf
- terraform/logs.tf
- terraform/main-gcp.tf
> Send logs to the gds-bq-reporting project

- terraform-dev/schemas/publishing-api/links.json
- terraform-staging/schemas/publishing-api/links.json
- terraform/schemas/publishing-api/links.json
Add the new column `link_set_content_id` to the `publishing-api.links` table, from upstream 
* [ADR-009](https://github.com/alphagov/publishing-api/pull/3232)
* [Part 1](https://github.com/alphagov/publishing-api/pull/3243)
> refactor: follow publishing-api ADR 009 step 1

- docs/arch/adr-001-consume-smart-survey-api.md
Recommended by https://trello.com/c/OO16uOUI/286-review-faas-architecture
[Rendered](https://github.com/alphagov/govuk-knowledge-graph-gcp/blob/adr-001/docs/arch/adr-001-consume-smart-survey-api.md)
> ADR-001: Consume Smart Survey

- docker/html-to-text/Gemfile
https://github.com/alphagov/govuk-knowledge-graph-gcp/security/dependabot/95
> chore: dependabot

- .github/workflows/actionlint.yml
- .github/workflows/diff-terraform.yml
- .github/workflows/html-to-text-lint-and-test.yml
- .github/workflows/parse-html-lint-and-test.yml
- .github/workflows/terraform-validation.yml
https://github.com/alphagov/govuk-knowledge-graph-gcp/security/code-scanning/1
https://github.com/alphagov/govuk-knowledge-graph-gcp/security/code-scanning/2
https://github.com/alphagov/govuk-knowledge-graph-gcp/security/code-scanning/3
https://github.com/alphagov/govuk-knowledge-graph-gcp/security/code-scanning/4
https://github.com/alphagov/govuk-knowledge-graph-gcp/security/code-scanning/5
> chore: Revoke GitHub Action permissions

- docker/http-to-bucket/app.rb
- docker/http-to-bucket/spec/app_spec.rb
The http-to-bucket Cloud Run service fetches a JSON response from an API, and then formats it as newline-delimited JSON (ndjson AKA JSONlines) for uploading into BigQuery.
Originally this was written and tested with the Smart Survey API, which returns an array of JSON objects, e.g.
```json
[{"foo": 1, "bar": true},{"foo": 1, "bar": true}]
```
and reformatted it as
```json
{"foo": 1, "bar": true}
{"foo": 1, "bar": true}
```
But the Zendesk API returns a single JSON object, e.g.
```json
{"foo": 1, "bar": true}
```
And the code accidentally formatted this as follows.
```json
[{"foo": 1},{"bar": true}]
```
This pull request handles both cases, by checking whether the API has returned an array or a singleton object.
> fix: http-to-bucket handle single JSON object
